version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=8080'
    image: 'ungar/tictactoe:${GIT_COMMIT}'
    ports:
      - '8080:8080'
      - '5432:5432'
    links:
      - 'postgres'
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
      - 'POSTGRES_USER=postgres'
    expose:
      - '5432'
